repos:
-   repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.11
    hooks:
    -   id: add-msg-issue-prefix
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
        - id: ruff     
          args: [
            '--fix',                 
            '--exit-non-zero-on-fix',
            '--select', 'I001', # I001 to sort imports  
            '--select', 'F401' # F401 to remove unused imports 
          ]
        - id: ruff-format        
            